;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_col
	.import		_ppu_on_all
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_write
	.export		_main

.segment	"RODATA"

L001B:
	.byte	$48,$45,$4C,$4C,$4F,$2C,$20,$57,$4F,$52,$4C,$44,$21,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0005:
	.byte	$43,$53,$39,$31,$53,$00

.segment	"CODE"

;
; char class[6] = "CS91S";
;
	jsr     decsp6
	ldy     #$05
L0006:	lda     L0005,y
	sta     (sp),y
	dey
	bpl     L0006
;
; pal_col(0,0x02); // set screen to dark blue
;
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     _pal_col
;
; pal_col(1,0x14); // fuchsia
;
	lda     #$01
	jsr     pusha
	lda     #$14
	jsr     _pal_col
;
; pal_col(2,0x20); // grey
;
	lda     #$02
	jsr     pusha
	lda     #$20
	jsr     _pal_col
;
; pal_col(3,0x30); // white
;
	lda     #$03
	jsr     pusha
	lda     #$30
	jsr     _pal_col
;
; vram_adr(NTADR_A(2,2));  // set address
;
	ldx     #$20
	lda     #$42
	jsr     _vram_adr
;
; vram_write("HELLO, WORLD!", 13); // write bytes to video RAM
;
	lda     #<(L001B)
	ldx     #>(L001B)
	jsr     pushax
	ldx     #$00
	lda     #$0D
	jsr     _vram_write
;
; vram_adr(NTADR_A(2,8));  // set address
;
	ldx     #$21
	lda     #$02
	jsr     _vram_adr
;
; vram_write(class, 5); // write bytes to video RAM
;
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _vram_write
;
; vram_adr(NTADR_A(2,12));  // set address
;
	ldx     #$21
	lda     #$82
	jsr     _vram_adr
;
; vram_put(0xAC); // write byte to video RAM
;
	lda     #$AC
	jsr     _vram_put
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; while (1) ;
;
L0036:	jmp     L0036

.endproc

