;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_col
	.import		_ppu_wait_frame
	.import		_ppu_on_all
	.import		_scroll
	.import		_vram_adr
	.import		_vram_write
	.import		_strlen
	.export		_put_str
	.export		_scroll_demo
	.export		_main

.segment	"RODATA"

L0059:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$43,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$31,$35,$00
L003E:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$41,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$31,$35,$00
L0047:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$41,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$32,$39,$00
L0062:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$43,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$32,$39,$00
L0035:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$41,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$30,$00
L0050:
	.byte	$4E,$61,$6D,$65,$74,$61,$62,$6C,$65,$20,$43,$2C,$20,$4C,$69,$6E
	.byte	$65,$20,$30,$00

; ---------------------------------------------------------------
; void __near__ put_str (unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_put_str: near

.segment	"CODE"

;
; void put_str(unsigned int adr, const char *str) {
;
	jsr     pushax
;
; vram_adr(adr);        // set PPU read/write address
;
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _vram_adr
;
; vram_write(str, strlen(str)); // write bytes to PPU
;
	jsr     pushw0sp
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	jsr     _vram_write
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ scroll_demo (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scroll_demo: near

.segment	"CODE"

;
; int x = 0;   // x scroll position
;
	jsr     push0
;
; int y = 0;   // y scroll position
;
	jsr     push0
;
; int dy = 1;  // y scroll direction
;
	lda     #$01
	jsr     pusha0
;
; ppu_wait_frame();
;
L000D:	jsr     _ppu_wait_frame
;
; y += dy;
;
	ldy     #$00
	lda     (sp),y
	ldy     #$02
	clc
	adc     (sp),y
	sta     (sp),y
	dey
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	sta     (sp),y
;
; if (y >= 479) dy = -1;
;
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$DF
	txa
	sbc     #$01
	bvs     L0016
	eor     #$80
L0016:	bpl     L0014
	ldy     #$00
	lda     #$FF
	sta     (sp),y
	iny
	sta     (sp),y
;
; if (y == 0) dy = 1;
;
L0014:	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0019
	tay
	lda     #$01
	sta     (sp),y
	tya
	iny
	sta     (sp),y
;
; scroll(x, y);
;
L0019:	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _scroll
;
; while (1) {
;
	jmp     L000D

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; pal_col(0,0x02);// set screen to dark blue
;
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     _pal_col
;
; pal_col(1,0x14);// pink
;
	lda     #$01
	jsr     pusha
	lda     #$14
	jsr     _pal_col
;
; pal_col(2,0x20);// grey
;
	lda     #$02
	jsr     pusha
	lda     #$20
	jsr     _pal_col
;
; pal_col(3,0x30);// white
;
	lda     #$03
	jsr     pusha
	lda     #$30
	jsr     _pal_col
;
; put_str(NTADR_A(2,0), "Nametable A, Line 0");
;
	ldx     #$20
	lda     #$02
	jsr     pushax
	lda     #<(L0035)
	ldx     #>(L0035)
	jsr     _put_str
;
; put_str(NTADR_A(2,15), "Nametable A, Line 15");
;
	ldx     #$21
	lda     #$E2
	jsr     pushax
	lda     #<(L003E)
	ldx     #>(L003E)
	jsr     _put_str
;
; put_str(NTADR_A(2,29),"Nametable A, Line 29");
;
	ldx     #$23
	lda     #$A2
	jsr     pushax
	lda     #<(L0047)
	ldx     #>(L0047)
	jsr     _put_str
;
; put_str(NTADR_C(2,0), "Nametable C, Line 0");
;
	ldx     #$28
	lda     #$02
	jsr     pushax
	lda     #<(L0050)
	ldx     #>(L0050)
	jsr     _put_str
;
; put_str(NTADR_C(2,15), "Nametable C, Line 15");
;
	ldx     #$29
	lda     #$E2
	jsr     pushax
	lda     #<(L0059)
	ldx     #>(L0059)
	jsr     _put_str
;
; put_str(NTADR_C(2,29),"Nametable C, Line 29");
;
	ldx     #$2B
	lda     #$A2
	jsr     pushax
	lda     #<(L0062)
	ldx     #>(L0062)
	jsr     _put_str
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; scroll_demo();
;
	jmp     _scroll_demo

.endproc

